from __future__ import annotations

import argparse
from pathlib import Path

from sciml.pinn import PinnConfig, train_pinn


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a physics-only PINN for plane-stress elasticity of a plate with a hole."
    )
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path("plate_fem") / "plate_data.mat",
        help="Path to plate_data.mat generated by the MATLAB preprocessing script.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs") / "pinn_physics",
        help="Directory where plots and checkpoints will be stored.",
    )
    parser.add_argument("--iterations", type=int, default=5000, help="Number of Adam iterations.")
    parser.add_argument("--learning-rate", type=float, default=1e-3, help="Initial learning rate.")
    parser.add_argument("--log-interval", type=int, default=100, help="How often to print the training loss.")
    parser.add_argument("--history-interval", type=int, default=100, help="How often to flush CSV training history.")
    parser.add_argument(
        "--checkpoint-interval", type=int, default=500, help="How often to save a resumable training checkpoint."
    )
    parser.add_argument("--resume-from", type=Path, default=None, help="Optional path to a checkpoint to resume from.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = PinnConfig(
        data_path=args.data_path,
        output_dir=args.output_dir,
        iterations=args.iterations,
        learning_rate=args.learning_rate,
        log_interval=args.log_interval,
        history_interval=args.history_interval,
        checkpoint_interval=args.checkpoint_interval,
        resume_from=args.resume_from,
        use_measurements=False,
    )
    artifacts = train_pinn(config)
    print("Saved artifacts:")
    for name, path in artifacts.items():
        print(f"  {name}: {path}")


if __name__ == "__main__":
    main()
